"Compiled on a Linux 4.4.160 system on 2018-11-16.\n"
"Available extensions:\n"
"	crypt add-on version 2.1 by Michael Glad and others\n"
"	Native POSIX Threads Library by Ulrich Drepper et al\n"
"	BIND-8.2.3-T5B\n"
